version: '3'

services:
  db:
    image: mariadb:10.5
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW # important, will not work without
    restart: always
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file:
      - db.env
    networks: 
      - backups

  redis:
    image: redis:alpine
    restart: always

  app:
    build: ./app
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - ./app/upload_max_filesize.ini:/usr/local/etc/php/conf.d/upload-max-filesize.ini
      - ./app/memory-limit.ini:/usr/local/etc/php/conf.d/memory-limit.ini
    environment:
      - VIRTUAL_HOST=${DNS_ADDRESS}
      - MYSQL_HOST=db
      - REDIS_HOST=redis
    env_file:
      - db.env
    depends_on:
      - db
      - redis
    networks:
      - proxy-tier
      - default
      - backups

  borgmatic_backup:
    image: b3vis/borgmatic
    volumes:
      - nextcloud:/mnt/source:ro
      - ${VOLUME_TARGET}:/mnt/borg-repository
      - ./backup/borgmatic.d:/etc/borgmatic.d
      - borg-config:/root/.config/borg
      - borg-cache:/root/.cache/borg
    environment:
      - TZ=${TZ}
      - BORG_PASSPHRASE=${BORG_PASSPHRASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - NEXTCLOUD_DATABASE=nextcloud
      - MYSQL_PWD=${MYSQL_ROOT_PASSWORD}
    restart: always
    networks:
      - backups
        
  cron:
    image: nextcloud:apache
    restart: always
    volumes:
      - nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
      - db
      - redis

volumes:
  db:
  nextcloud:
  html:
  borg-cache:
  borg-config:

networks:
  backups:
