version: '3'
services:
  borgmatic_backup:
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor:unconfined
      - label:disable
    devices:
      - /dev/fuse:/dev/fuse
    command: /bin/sh
